# Generated by Django 4.2.4 on 2023-08-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastImage',
            new_name='PostImage',
        ),
    ]
