# Generated by Django 4.2.4 on 2023-08-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_news', '0002_rename_pastimage_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
