# Generated by Django 4.2.4 on 2023-08-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_news', '0003_rename_category_post_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postimage',
            unique_together=set(),
        ),
    ]
