# Generated by Django 4.2.4 on 2023-08-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_news', '0005_alter_postimage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postimage',
            unique_together=set(),
        ),
    ]
