version: "3"


services:
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1443:1443
    networks:
      - app
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8080:5000
    environment:
      PYTHONBUFFERED: "1"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app
    env_file:
      - .env
    tty: true



  db:
    image: mysql:latest
    ports:
      - 3308:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app


networks:
  app:
    driver: bridge
